#cloud-config
write_files:
  - path: /tmp/install_openvpn.sh
    permissions: '0755'
    encoding: base64
    content: |
      ${install_script_base64}
  - path: /etc/profile.d/startup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      FLAG_FILE="$HOME/.startup_complete"
      if [ ! -f "$FLAG_FILE" ]; then
          echo "Running OpenVPN installation script..."
          sudo bash /tmp/install_openvpn.sh --as-version=${openvpn_version}
          touch "$FLAG_FILE"
      fi
runcmd:
  - sudo chmod +x /tmp/install_openvpn.sh
