#cloud-config
write_files:
  - path: /etc/profile.d/startup.sh
    permissions: '0755'
    content: |-
      #!/bin/bash
      FLAG_FILE="$HOME/.startup_complete"
      if [ ! -f "$FLAG_FILE" ]; then
          echo "Running OpenVPN installation script..."
          sudo  bash <(curl -fsS https://packages.openvpn.net/as/install.sh) --yes --as-version=2.14.2
      fi
