#cloud-config
write_files:
  - path: /tmp/install_openvpn.sh
    permissions: '0755'
    encoding: b64
    content: ${install_script}

  - path: /home/ubuntu/startup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      if [ ! -f /home/ubuntu/.startup_complete ]; then
        echo "Running OpenVPN installation script..."
        sudo bash /tmp/install_openvpn.sh --yes
        touch /home/ubuntu/.startup_complete
      else
        echo "OpenVPN installation already completed."
      fi

runcmd:
  - echo ". /home/ubuntu/startup.sh" >> /home/ubuntu/.bashrc