#cloud-config
write_files:
  - path: /tmp/install_openvpn.sh
    permissions: '0755'
    content: |
      ${install_script}

  - path: /etc/profile.d/first_login.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      FLAG_FILE="$HOME/.first_login_done"
      if [ ! -f "$FLAG_FILE" ]; then
        echo "Running OpenVPN installation script..."
        sudo bash /tmp/install_openvpn.sh --yes
        touch "$FLAG_FILE"
      fi

runcmd:
  - sudo chmod +x /tmp/install_openvpn.sh
